services:
  - type: web
    name: your-game-app
    env: node
    buildCommand: | 
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production